### ISSUE TITLE
Feature request: Add 'alignment' for "textbox" of Json template

### ISSUE THREAD

**Issue by LeftPinkie** [OpenEPaperLink/OpenEPaperLink#285]
In the Json template, please add "alignment" attribute to the "textbox" object like it has for "text". For example:
```
{ "textbox": [x, y, w, h, "text", "fontname" }
{ "textbox": [x, y, w, h, "text", "fontname", color ] }
{ "textbox": [x, y, w, h, "text", "fontname", color, line height] }
{ "textbox": [x, y, w, h, "text", "fontname", color, line height, alignment] }
```

**Comment by nlimper** [comment]
What's your usecase? IMHO, a paragraph text should (almost) always be left aligned.
For headlines etc, you can use "text" which can be left/center/right alinged.

**Comment by LeftPinkie** [comment]
If I have a multi-line description, I would like to have it wrap and align center or right.

**Comment by nlimper** [comment]
Done! (in https://github.com/OpenEPaperLink/OpenEPaperLink/commit/30812dff49621fc0a39c7fba8fffef922bbe345b)
`{ "textbox": [x, y, w, h, "text", "fontname", color, line height, alignment] }`
0: left, 1: center, 2: right
