### ISSUE TITLE
[COSMETIC] Errormessage after update "tagtype definitions"

### ISSUE THREAD

**Issue by mcm1957** [OpenEPaperLink/OpenEPaperLink#297]
When executing "update tagtype definitions" an error is displayed caused be standard README.mdas this file is not json formatted for sure:

![image](https://github.com/jjwbruijn/OpenEPaperLink/assets/28575778/30c27764-5012-43f7-9cb6-589def9744f9)

Seems to cause no harm as all jsons start with numbers and are processed before README.md anyway -  but I would suggest to ignore files not ending with .json to avoid this error.

**Comment by aw750s** [comment]
same problem in version 2.60b

**Comment by nlimper** [comment]
fixed in an upcoming commit, only processes files ending with .json
