### ISSUE TITLE
Layout of hanshow nebular changed

### ISSUE THREAD

**Issue by teichtaucher** [OpenEPaperLink/OpenEPaperLink#305]
Recently I got an 3.5" hanshow nebular pricetag. Orignally I wanted to reflash it with alternative firmware. But after some cuts into the case I found out that they changed the layout - the soldering pads for reflashing are not there as shown in this video:
https://www.youtube.com/watch?v=WRfZJ4xyYwc

![IMG_20240425_130927](https://github.com/jjwbruijn/OpenEPaperLink/assets/63404380/44b3c475-ad59-4cb3-b299-9d8ec56a24c4)

There are three on the left top side of the controller. Could they be used for reflashing?

**Comment by nethomas1968** [comment]
Oh, that's interesting.
I only have the other type of 3.5 inch Hanshow Nebular. The firmware in this repo doesn't actually work with this type of screen anyway, so not being able to flash it isn't going to inconvenience you.
Can you take the while thing apart and see if they have moved the 6 programming pads to some other place on the board ?

**Comment by ximon** [comment]
I have the same model which I've removed from its case, here's a photo of the board:
![PXL_20240618_170623886 MP](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/75038/f4844cbf-997f-4370-8a99-9013de3c0c51)

**Comment by teichtaucher** [comment]
Sorry, I missed that topic. I broke the casing of mine completely to see the contacts. It's not so easy as it was with the older revisions because the display is glued to the PCB and the battery is not a knob cell. So I was uncertain if I break everything.
Nevertheless my layout is the same as @ximon. I managed to flash the firmware and could also see the initial screen.
But there was a misunderstanding. I thought the tag works with BLE and I can control it via PC or smartphone.
This does not work and I didn't want to built up this access point. So I stopped here.
But I'm still watching OpenEpaperLink. In principle Hanshow has also BLE interface. Maybe there will be a custom firmware version which can be controlled via BLE and PC.

**Comment by frr032** [comment]
Hi all. Im a total tag newbe and have had difficulty understanding what tags work and mostly where to find them. My application is displaying messages from home assistant.  I was able to get a few hanshow nebular tags that look like tags in this post from a local store. I'm hoping to flash them and use with openepapeelink. One had a broken display so I disassembled it. See pics.  I have Nic's AP/flasher. How would I flash these tags? 

![20240825_131820](https://github.com/user-attachments/assets/863cccd5-fe91-444a-88d2-8f2fe3f4404f)
![20240825_173711](https://github.com/user-attachments/assets/60d798bb-82b4-42a5-8dcf-e9911a1a5a2c)
![20240825_173541](https://github.com/user-attachments/assets/db406a6a-2ab4-4e2f-b248-8f81e78f95d8)
![20240825_173558](https://github.com/user-attachments/assets/ca62ef87-f0be-41cb-bcea-a04b3685a706)
![20240825_174110](https://github.com/user-attachments/assets/f2255572-0784-4557-bff8-e88f64b328b5)
![20240825_174010](https://github.com/user-attachments/assets/cc7a6179-ef41-4c5b-97ec-15061da3c258)

**Comment by teichtaucher** [comment]
You're having a model with the PIN layout which ist also shown in this video:
https://www.youtube.com/watch?v=WRfZJ4xyYwc
In this video you can also see how to flash it.
As you already cracked open you display the flash PIN connectors are shown on your second to last image.

**Comment by frr032** [comment]
teichtaucher  Thank you so much for the reply!

The [link ](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa2p4SndmeTd5TV9tcGRKQll4SDVHUmh0Zk9rUXxBQ3Jtc0trWnlGSWJXdXZITzlWNWtzV0lHemxHTFJLcm1zSHNRY3pyZzF0LTVPRXQxVzVjVU94eHM5c2lQeVY3eTIycURFMmg5N0N4dDVxZWJFOGRHb0FHXzRVS3dEcWdSczRqaTlFY0c2VVY5SHRPWV9NbFk4WQ&q=https%3A%2F%2Fgithub.com%2Fjjwbruijn%2FOpenEPaperLink%2Fblob%2Fmaster%2Fbinaries%2FTag%2FTLSR_HS_35_ALPHA.bin&v=WRfZJ4xyYwc) to the tag firmware in this YouTube video above is a bad link.  I see that there are other files in it's parent folder that look similar (pic below).  

Which firmware should I use?

Also; I have the Mini-AP-v4 Access Point w/ Tag Flasher. It has a breakout board (pic below) for the pins but none of them are labeled SWS.

How should I wire this breakout board to the tags?  Is the TXD wired to the SWS pin on the tag?

Do I need to go throw the steps like you have in the video and reverse the pins to reset the tag the flash it or can I just flash it?

Thanks again with helping me get started with OPEL!  Frank



![image](https://github.com/user-attachments/assets/c713f580-505c-411d-b96b-2c00e0da92cb)

![image](https://github.com/user-attachments/assets/de927820-bcf3-4b5e-b1bf-0de3c4543294)

**Comment by teichtaucher** [comment]
Hi, I already had a discussion in another thread regarding the Firmware for Nebular 350: https://github.com/atc1441/ATC_TLSR_Paper/issues/50#issuecomment-2308758937
You can use the info of this thread. I can remember that I used something with "350 inverted".
Regarding the MiniAP I unfortunately can't support - I stopped my Investigation before 😉

**Comment by hacki033** [comment]
Hi
I have the same tag as in the pictures above, with the HS9118 chip.

Where can I find the code to flash the open epaper firmware on it?

Or
better still a step by step guide on how to flash it correctly and then integrate it into home assistant?

That would be great. Because I am a complete novice.

Thank you very much

**Comment by teichtaucher** [comment]
Hi,
you can find the files to flash here:
https://github.com/OpenEPaperLink/Resources/tree/main/binaries/Tag

I had a Hanshow Nebular 350 (used in Aldi in Germany). I can remember I used something like [TLSR_HS_BWY_35_inverse.bin](https://github.com/OpenEPaperLink/Resources/blob/main/binaries/Tag/TLSR_HS_BWY_35_inverse.bin)

I was able to flash something and to see something on the screen. But: You also need an Access Point because you can't access it via bluetooth. This APhas to be assembled by yourself using two ESP32.

I stopped here because the effort was to big for me. But I'm still looking for a battery driven eInk display which can be contacted via BLE or similar.

**Comment by hacki033** [comment]
Thank you for your quick reply.

How did you get the device into flash mode?
When I connect it to my USB to TTL and try to replace or flash, the device shows no reaction (the led wanted to flash?)
When I connect the rx from adapter, the indicator light on the TTL adapter flashes shortly after the power is connected during the day. But I have not been able to read anything via minicom, for example. Do you know which baud rate you had?
