### ISSUE TITLE
update tag type definitions- error on readme.md

### ISSUE THREAD

**Issue by rvdv01** [OpenEPaperLink/OpenEPaperLink#328]
**Describe the bug**
Using 2.60b, when clicking’update tag type definitions’, an error is thrown

**To Reproduce**
Go to update
Click ‘update tag type definitions’

**Expected behavior**
The update runs normally

**Screenshots**
![IMG_0126](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/16882848/004c6226-707a-4aa4-8e84-70682fea84d1)

**Comment by nlimper** [comment]
You can ignore the error. It would be better to skip readme.MD but it doesn’t do any harm.

**Comment by rvdv01** [comment]
> You can ignore the error. It would be better to skip readme.MD but it doesn’t do any harm.

Ignoring things is what I do best :-) 

Since the error message was the last line, I was unsure if it crashed after encountering readme.md or if there were simply no files on the server that started with an ‘s’.
Also, when I retried the download, the system again said ‘updating version 0 to 1’ for every definition file, so it seemed to me some process perhaps hadn’t finished properly (eg. a process that notes the version of all definition files in some kind of database).

Thanks for the quick reply.
