### ISSUE TITLE
How to re-write MAC address to a tag?

### ISSUE THREAD

**Issue by 42Network** [OpenEPaperLink/OpenEPaperLink#330]
I have a few ST-GR2900 tags. One of them has changed its own MAC address to all zeros, possibly as a side effect of its batteries being run down too long. After replacing the batteries, it seems to work fine, but it is awkward that it now appears in the tag list as "0000000000000000".  I'm frankly surprised that all functions still work with what I think is likely an invalid MAC.

Is there a known method to re-write its MAC address (which I can just copy from what is printed on the case) into the firmware?

Using the AP Flasher, I was even able to upgrade the firmware on this tag to the latest version, but it still kept all-zero MAC.

![image](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/35043496/9bd41891-ce7d-4181-b501-97d9ae9b6572)

**Comment by davedarko** [comment]
My way currently is, with python on a macbook:

Use files from this folder:
https://github.com/OpenEPaperLink/OpenEPaperLink/tree/master/Tag_Flasher

if you don't have an info page dump, use this:
python3 OEPL-Flasher.py -z -i -p /dev/cu.usbmodem01 read info.bin

patch the mac address of the info page
python3 patch_mac.py --zbs243 -mac YOURMACHERE info.bin

and write it back on the tag
python3 OEPL-Flasher.py -z -i -p /dev/cu.usbmodem01 write info.bin

might contain typos, I have a cold - and there's probably other ways, hope it helps
