### ISSUE TITLE
BLE (Gicisky) size support

### ISSUE THREAD

**Issue by ptahbe** [OpenEPaperLink/OpenEPaperLink#338]
The wiki states that the following is supported :

BLE based (Gicisky/Picksmart)
    2.13" TFT
    2.13" EPD
    2.9" EPD
    4.2" EPD

There are other sizes, like 7.5 and 10.2, available from Gicisky. Are these also supported?

**Comment by jonasniesner** [comment]
Not yet but they might be supported in the future

**Comment by atc1441** [comment]
@ptahbe 
I could also add them if I got my hands on one of each, but currently there is no plan to spend that money from my end

**Comment by jrtraynor** [comment]
> I could also add them if I got my hands on one of each, but currently there is no plan to spend that money from my end

@atc1441   I have one of the 7.5 BLE units here. Is there anything I could do, scan/capture to help?  Can confirm the 7.5 does show up just in the oepl web page but loads as a 296x128 fw:257 0x101 , Also doesn't update the units screen.

**Comment by atc1441** [comment]
You can test here: https://atc1441.github.io/ATC_GICISKY_Paper_Image_Upload.html

**Comment by jrtraynor** [comment]
Got some partial success
Send CMD: 01
Got bytes: 01f400
Send CMD: 0200770100000000
Got bytes: 0200
Sending now stage 3
Send CMD: 03
Got bytes: 050000000000
Send CMD: 04
Got bytes: 0405

Using 800x480. compress,mirror and 2 colour. It does update the screen. but it comes out upside down and inverted with both the red and black txt coming out as white.  Do the same as single colour get the same just with a red/black noise background.
![PXL_20240622_113516426](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/65301215/51f881a8-448a-4af7-bd81-ab5f8f787cee)
![PXL_20240622_105700928](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/65301215/73408ff3-b79b-47b4-9b93-dca3322aadfd)

Not sure what to try next

**Comment by atc1441** [comment]
Please get the advertising data from it

**Comment by jrtraynor** [comment]
Is this what you are looking for:

![Screenshot_20240622-141644](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/65301215/1aa58107-f6ea-4a5a-8009-4f53213369ed)

**Comment by atc1441** [comment]
Thanks, its at least added half way to the web uploader that way.

**Comment by ZoneMR** [comment]
I too would love to see support for the 7.5" Gicisky ESL.

I'm happy to help in any way to contribute this - where do I start?
