### ISSUE TITLE
Provide examples for icons and symbols

### ISSUE THREAD

**Issue by psfales** [OpenEPaperLink/OpenEPaperLink#339]
**Is your feature request related to a problem? Please describe.**
The documentation for jsonupload says.  "if you want icons and symbols, the Font Awesome font works quite well."  However, I can't figure out how to display icons and symbols.   I also can't figure out how to access the symbols in weathericons.ttf

**Describe the solution you'd like**
Add some examples in the documentation showing how to display icons and symbols like the degree symbol, arrows, clouds, battery levels, etc.

**Comment by LeftPinkie** [comment]
I wrote up this tutorial... see if it's clear and helpful. It has examples for both the include weathericons and Font Awesome. But you should be able to use this example for any TrueType font.

**Comment by psfales** [comment]
For some reason, I can't see the link in the July 8 comment.  When I click on it, it takes me to a blank "create a new page" on the Wiki.  Not sure what I'm missing.  :-(

**Comment by nlimper** [comment]
Read the URL. Go to the Wiki. Search around, and you will find it anyway. (the page was renamed)
I did that for you: https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/Uploading-%26-Using-Custom-Fonts%2C-with-examples

**Comment by psfales** [comment]
Awesome!   Thanks!
