### ISSUE TITLE
Gerber for S3_C6_NanoAP Variant 2 and 2.2

### ISSUE THREAD

**Issue by LeftPinkie** [OpenEPaperLink/OpenEPaperLink#340]
Does anyone have the Gerber files for the variant 2 and 2.2 of S3_C6_NanoAP as pictured in:

https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/Hardware/S3_C6_NanoAP%20Case[/V2_Case_image_Pal_Hamre.jpg

https://github.com/OpenEPaperLink/OpenEPaperLink/blob/master/Hardware/S3_C6_NanoAP%20Case/V2_2_Case_Image_By_Viktor_Knall.png

Maybe @atc1441?

**Comment by nikkisstuff** [comment]
here you go

https://github.com/OpenEPaperLink/OpenEPaperLink/tree/master/Hardware/S3_C6_NanoAP%20by%20ATC1441

**Comment by bjoern-r** [comment]
The gerber zip in the `S3_C6_NanoAP by ATC1441` folder only contains the square V1 variant and not the v2 variant with the 45 degree USB-C connector.
