### ISSUE TITLE
Feature request: Send tag MAC in URL

### ISSUE THREAD

**Issue by LeftPinkie** [OpenEPaperLink/OpenEPaperLink#341]
Requesting a feature of the Tag JSON Template to send the tag's MAC address as part of the URL (query string). For example, the URL would be something like:
```
https://domain/path/?tag_mac={tag_mac}
```

where `{tag_mac}` would be the tag's MAC address, like '000078364E0CDADC'.

**Comment by nlimper** [comment]
The mac is passed as a form field, just as the json template itself. I don't think there is an added benefit to pass it in the query string.
