### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by noha23** [OpenEPaperLink/OpenEPaperLink#343]
I have a bunch of solum m3 price tag (EL029H3WRA) and ESP32-S3-WROOM-1 N16R8. I have flashed the esp32 as an ap and flasher. But now i am stuck because i seem not to be able to find out by myself what pin of the display connect to what pin of the esp32 to flash the custom firmware of the display. Please help
![20240630_235106](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/96893897/8f5c8bfd-6015-4ab9-b3ff-4a638c63836f)

**Comment by LeftPinkie** [comment]
@noha23 You can find references here: https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/Access-point-pinouts. Also there is a list of access points and flashers built by other: https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/Building-an-Access-Point. Hope that helps.

**Comment by LeftPinkie** [comment]
Just out of curiosity, where did you get these M3 tags? Are you will to sell some to me?

**Comment by BigSpice** [comment]
> Just out of curiosity, where did you get these M3 tags? Are you will to sell some to me?

I have more tags than I can handle here XD.

Sad part is I dont have an s2 based board, so im trying to find a way to use a _[WROOM-32]_ or a _[D1 MINI]_ ,to flash and create an AP for these tags. :(.

Ive also made a modified JIG for all of the pins available for the M3 2.2 Pinout.
As well as adjustments to use regular aruino cables for faster testing and debugging.

![image](https://github.com/user-attachments/assets/b2803599-e3e7-456d-9305-b95d7acaeffe)

**Comment by LeftPinkie** [comment]
Where are you located? I'm in the USA (Los Angeles). I would like take off your hands (buy) some of the Solum M3 tags. Also I can source and purchase the ESP-32 S3 and C6 modules for you.

**Comment by BigSpice** [comment]
> Where are you located? I'm in the USA (Los Angeles). I would like take off your hands (buy) some of the Solum M3 tags. Also I can source and purchase the ESP-32 S3 and C6 modules for you.
Thank you so much :D,
Im here in Ottawa ON.
Send me an email, im fully able to send you some.
jordan.k.m@proton.me

**Comment by enzo996** [comment]
Anybody with backup from infopage.bin / uicr from this tag please? i have a broken one, was locked. maybe i can get it working again..
