### ISSUE TITLE
Feature request: Hanshow Nebular 350 Temperature reading.

### ISSUE THREAD

**Issue by mukowman** [OpenEPaperLink/OpenEPaperLink#345]
The Hanshow Nebular 350 tags are reporting a temperature of 0.
I have checked and can confirm the ATC1441 BLE firmware is able to report temperature. So would love for this to come across to OEPL.

**Comment by SLboat** [comment]
Does it also have a tlsr8359 kernel processor?

**Comment by atc1441** [comment]
The Screen used in some Displays are not able to get the temperature, will be implemented where it is possible but its just not possible on all
