### ISSUE TITLE
Flashing Chroma 29 tag using OpenEPaperLink_Mini_AP_v4

### ISSUE THREAD

**Issue by LeftPinkie** [OpenEPaperLink/OpenEPaperLink#347]
I have the Chroma 29 tag...
serial #: JA0xxxxxxxB
board rev: edk286 Issue 9 220-0067-09
EPD panel: WF0290T1PBZ01
![20240704_140323](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/17230489/25c54d84-4833-4f9a-bac4-5136da1bb02a)
![20240704_135254](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/17230489/4dc0c2e0-3801-47d9-b26d-f90d30704450)
![20240704_134551](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/17230489/2996810a-9437-490f-b199-5c5ac225f0d7)
![20240704_135037](https://github.com/OpenEPaperLink/OpenEPaperLink/assets/17230489/125a7cc4-f7fa-4970-a9f0-bfe8e140e054)

Per the wiki https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/2.9%22-Chroma-29 by @skiphansen, this tag should be supported by the SubGhz Beta FW.

I have the AP OpenEpaperLink basic tag programmer kit (https://www.tindie.com/products/electronics-by-nic/openepaperlink-basic-tag-programmer-kit/) by @nlimper, which is OpenEPaperLink_Mini_AP_v4 environment.

Can you tell me how to connect the Chrona29 tag to the AP so that I can flash the tag?

**Comment by nlimper** [comment]
The tag programmer kit is (currently, as long as nobody adds it) only suitable for flashing Solum tags.
For Chroma: https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/Chroma-Series-SubGhz-Tags#flashing-cc1110-based-chroma-tags
