### ISSUE TITLE
FTP server for Access Point FW

### ISSUE THREAD

**Issue by LeftPinkie** [OpenEPaperLink/OpenEPaperLink#349]
Request to add FTP server to access point fw. This will allow us to upload & manage files on the AP. While the edit page (`http://{ap_ip_address}/edit`) is adequate to manage one file at a time, FTP would allow us to upload, delete, download multiple files. Also, please allow ability to create/delete directories.

**Comment by jonasniesner** [comment]
I have to close this as not planed for now. The ESP is at its limits at the moment and adding FTP would most likely push it over. We maybe can think about it after S2 based APs are discontinued.

**Comment by LeftPinkie** [comment]
Maybe include in the AP binary but not activated / enabled by default... and have it as an option to enable via the admin page
