### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by BigSpice** [OpenEPaperLink/OpenEPaperLink#352]
**Is your feature request related to a problem? Please describe.**
Currently have the Very popular _WEMOS D1 MINI_ and an _ESP32 - WROOM-32_ Boards.
Access to S2 based boards in my area is unavailable for various reasons.

**Describe the solution you'd like**
Possible support for the _ESP32_ or _D1 MINI_ based boards in the flashing of the Tags.
These are one of the more abundant board types, I understand implemetation would expand the project further.

**Describe alternatives you've considered**
Fully understanding of any technical limitations due to either communication or broadcast hardware.
Use of an _FTDI_ flasher to make use and edit the firmware flasher code to upload and work on a _D1 MINI_.

**Additional context**
Any help toward walls I am facing or dropped research material toward this topic would be the best and most appreciated response.

**Comment by jonasniesner** [comment]
Do you want to use those boards as a Flasher or AP?

**Comment by BigSpice** [comment]
> Do you want to use those boards as a Flasher or AP?

Hopefully the D1 Mini as my flasher and the ESP32-WROOM as the AP.

**Comment by BigSpice** [comment]
Above was scrapped.

Unrelated but unsure where to contribute ongoing research to the community.
Going to append here.
New tag types.
More to come.
## FCC: 2AFWN-EL016H4WRC
### MODEL: EL016H4WRC
![20240819_164417](https://github.com/user-attachments/assets/f00631c2-3452-4a0a-b83a-35c6ecddec48)
![20240819_164436](https://github.com/user-attachments/assets/8fd081e5-19e7-40ef-895e-3806b18df1c7)
![20240819_164720](https://github.com/user-attachments/assets/9e9ad7de-01b9-489d-9a79-17908a94b96d)
![20240819_164907](https://github.com/user-attachments/assets/b3c825d5-f5da-4e78-852e-339ca53dbfcd)
![20240819_165020](https://github.com/user-attachments/assets/3aeb6291-3ec9-4283-9145-e4777080de43)
## FCC: 2AFWN-EL022F3WRA
### MODEL: ELF22F3WMA
_Unfortunately the SOC is locked down according to @LeftPinkie._

![20240819_165048](https://github.com/user-attachments/assets/4c24661e-5c37-4ebf-a57c-aa5c9135e2e6)
## FCC: 2AFWN-TG-GR22
### MODEL: TG-GN22F
![20240819_165108](https://github.com/user-attachments/assets/9a1266d7-1ca2-4743-9433-45aa3280db64)
![20240819_165224](https://github.com/user-attachments/assets/dbf8d4c8-e70d-4244-8283-861a812e9747)

**Comment by nlimper** [comment]
New tagtypes are always welcome :-)
You can do a pull request in case of enhancements, or add them to the [wiki](https://github.com/OpenEPaperLink/OpenEPaperLink/wiki) if you want to document stuff. 
(I'm closing the issue, as it's not an issue ;-) )
