### ISSUE TITLE
Feature request: Building a Custom ESL with ESP32 and 7.5-inch E-ink Display

### ISSUE THREAD

**Issue by hugodemiglio** [OpenEPaperLink/OpenEPaperLink#358]
Hello,

I am interested in building a custom electronic shelf label (ESL) using an ESP32, a driver board, and a 7.5-inch e-ink display that is compatible with Waveshare. I have reviewed the OpenEPaperLink documentation, but most examples seem to focus on using existing market-ready tags, and I couldn't find instructions on how to set up a custom configuration in the wiki.

I would like to create my own ESL setup with the following components:

ESP32: As the main controller
Driver Board: Hat to interface with the e-ink display
Waveshare-Compatible 7.5-inch E-ink Display

Could you please provide guidance on the following:

Is it possible to use OpenEPaperLink to control a custom ESL setup with these components?
Are there any specific instructions or examples available for interfacing a Waveshare-compatible e-ink display with the ESP32 using OpenEPaperLink?
What are the key considerations and potential challenges I should be aware of when building this setup?
Thank you for your assistance!

Best regards,
Hugo.

**Comment by nlimper** [comment]
It's possible to use the OEPL protocol to send info to such a display. But if it's the only display you use, it's a bit overkill to use a OEPL access point, as the esp32 connected to your waveshare display will be powerfull enough to process everything.
In any case, if you want to use OEPL for this, you have to fiddle with some software on your esp32/waveshare device. First make sure you can display something on your epaper display at all (probably using one of the examples provided by Waveshare). After that, here is an example for an esp32 firmware to use the OEPL protocol to drive a TFT screen (and a bluetooth printer... but that's not relevant here). With that firmware as an example, you should be able to put something together. Good luck!
