### ISSUE TITLE
Feature request: Change port from 80

### ISSUE THREAD

**Issue by ledyr-sthlm** [OpenEPaperLink/OpenEPaperLink#361]
I have several AP and would like to communicate over internet, Would it be possible to ask for a port option in network settings?

**Comment by jjwbruijn** [comment]
While it would be possible, I see no real benefit here. You shouldn't make the accesspoint publicly available over the internet, a different port is no substitute for security. Look into solutions like VPN (a cheap router running OpenWRT would be enough to make this happen)
