### ISSUE TITLE
Feature request: Eink 23"

### ISSUE THREAD

**Issue by SvetZitrka** [OpenEPaperLink/OpenEPaperLink#364]
I would like to use Home Assistnat to share tasks in the family through a large Eink board.

The biggest one we found is this one https://www.ebay.com/itm/286013702072

Would OpenEPaperLink be able to control it?

**Comment by atc1441** [comment]
the linked display is a segment display only. 

No images can be displayed on it. 

Because of that it makes no sense to support it

**Comment by SvetZitrka** [comment]
What is the largest eink display available so far where images can be displayed?

**Comment by nlimper** [comment]
Which is supported by OEPL? That might be the Solum M3 12.2" 
But that's all in theory, because the bigger displays (or, even the smaller displays) are almost impossible to find.

**Comment by atc1441** [comment]
@SvetZitrka feel free to send me a Mail to atc1441@gmail.com for a 12,2" variant, got few of them
