### ISSUE TITLE
Feature request: Virtual ePaper tag?  

### ISSUE THREAD

**Issue by gitpower2017** [OpenEPaperLink/OpenEPaperLink#368]
Is there an emulated tag so that you can test the json configuration without a real tag?

**Comment by nlimper** [comment]
There isn't.
If you use an AP with a TFT screen (like the YellowAP or the mini AP v3/4), you can use that to test, as the tft screen is also usable as a tag.

Or if you have a spare esp32 and tft screen on hand, you can use this:
https://github.com/nlimper/TFTtag-for-OpenEpaperLink
It acts like a tag, and updates instantly (no need to wait for the next checkin if you change content). The script also contains some code to send OEPL content to a label printer, so you have to remove that part. ;-)
