### ISSUE TITLE
Display remains white when I use % as a character

### ISSUE THREAD

**Issue by gitpower2017** [OpenEPaperLink/OpenEPaperLink#369]
Hello. 

As soon as I want to send the character % as json.
e.g. 55% humidity. The display remains blank.

Must a >> % << be specially protected.

**Comment by nlimper** [comment]
For the json string, the normal encoding applies (like `"` -> `\"`). But on top of that: how do you send the json to the AP? If you craft your own HTTP POST call, note that you have to use the proper escape sequences for the POST parameters. In `application/x-www-form-urlencoded` content, that's the percent encoding: https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding.
If that's not your situation, please provide an example, and describe how to reproduce.
