### ISSUE TITLE
Feature request: Emulator for an ePaper display (virtual display) ?

### ISSUE THREAD

**Issue by gitpower2017** [OpenEPaperLink/OpenEPaperLink#371]
Especially the development of a nice display with json commands requires many updates of a display. 
If you want to write a visualisation for a display that you do not own yourself, this is also difficult or even impossible

Not only does such an update take a relatively long time, it also drains the battery life.

There is already a small preview in the Webgui, perhaps it can be extended to a virtual display?

**Comment by jonasniesner** [comment]
I was thinking about this feature for the home assistant integration. Do you use Home Assistant or just the AP directly?

**Comment by gitpower2017** [comment]
I use the AP directly.
A solution in the AP is also much more flexible, you can manage with fewer dependencies. Everyone benefits from it.
