### ISSUE TITLE
Feature request: API

### ISSUE THREAD

**Issue by hrueger** [OpenEPaperLink/OpenEPaperLink#374]
**Is your feature request related to a problem? Please describe.**
Hi, first of all, thanks for this very cool project! We just built a spaghetty ap and are very happy with how it is working!
Is there any json rest api available? We'd like to integrate it with our other infrastructure (not based on homeassistant).

**Describe the solution you'd like**
A REST api taking and responding with json for querying tags, tag status and pushing updates. Ideally with an OpenAPI 3 spec, so that clients can be generated ;-)

**Describe alternatives you've considered**
Connecting to the websocket and sending http requests with form data, but I'd expect that to be more hacky and probably not backwards-compatible with firmware updates.

**Additional context**
-

**Comment by nlimper** [comment]
Using the websocket and sending HTTP GET/POST requests mimicing the AP frontend is the way to go. The Home Assistant plugin also uses those. They will not change (at least, I'm aware that other applications will break if changing them, so we will avoid it reasonably possible).
And there is also these:
https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/Image-upload
and
https://github.com/OpenEPaperLink/OpenEPaperLink/wiki/Json-template
