### ISSUE TITLE
Day ahead electricity price shows "nan" instad of current price per kWh

### ISSUE THREAD

**Issue by mountaindude** [OpenEPaperLink/OpenEPaperLink#380]
**Describe the bug**
Instead of showing current cost/kWh, the display shows "nan/kWh"
The bar chart updates correctly, so it seems data is received from the source, but the current value is no longer calculated correctly.
The vertical line indicating "now" is also missing.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/c75e55d2-381c-4418-90a8-c6f956be1662">

**To Reproduce**
<img width="375" alt="image" src="https://github.com/user-attachments/assets/b8b1bc67-0883-4316-b18c-ae80d7416fdc">

C6 chip updated to latest version.
Tag type definitions updated.

**Expected behavior**
Up until a week or two ago the correct, current price was shown in the display.

**Additional context**
I would guess the issue occurs [here](https://github.com/OpenEPaperLink/OpenEPaperLink/blob/8986967a4d364618c979a3636ecea44a21dd8df5/ESP32_AP-Flasher/src/contentmanager.cpp#L1575) somewhere.

**Comment by nlimper** [comment]
Thanks for your report. The upstream API provider (ENTSOE) has unexpectedly migrated their transparancy platform to a new server (https://transparency.entsoe.eu/news/widget?id=66e3ecae61d4cd1be808f94d). I haven't found the new API entry point, will dive into it in the next few days. When fixed, your display will start working again without intervention. Please stand by. :-)

**Comment by AseKarlsson** [comment]
Thanks @nlimper!

**Comment by nlimper** [comment]
After a few days, the error solved itself, probably after ENTSOE debugged their migration.
Can you confirm it's also working again for you? (if not, please tell me which country)

**Comment by mountaindude** [comment]
Yup, works here in Sweden. 
That was a convenient solution, things fixing themselves :)
