### ISSUE TITLE
Support for the SES Imagotag VUSION 2.1 BWR BU431 EDB1-0210-A

### ISSUE THREAD

**Issue by rubin110** [OpenEPaperLink/OpenEPaperLink#384]
Not sure if this would be the right spot to post this, I didn't see a discussions section for this repo, so I apologize if this should be going somewhere else. Also sorry I'm relatively new to this project and these devices.

I found this tag. I'm curious if it's supported. And if not, does anyone want it mailed to them to attempt to hack it?

Stuff from the back label:
SES Imagotag
VUSION 2.1 BWR BU431
Model: EDB1-0210-A

Chip:
Qualcomm
QCC710
002
E4148XD

[FCC filings](https://fcc.report/FCC-ID/2ACQM-EDB1-0210-A). I couldn't find a data/product sheet on this version (VUSION?).

 I'm assuming it's BLE. There's an LED in the top left corner. The pogo pads on the back are really scattered which is annoying. :(

![image](https://github.com/user-attachments/assets/3260579c-8e9f-4b33-ae58-1b44d0267c2c)
![image](https://github.com/user-attachments/assets/4ae18eea-a05d-47fd-a1ea-6f61af279910)
![image](https://github.com/user-attachments/assets/b4239588-d0a4-40cf-99c5-d2eaa8d6e467)
![image](https://github.com/user-attachments/assets/3ec47e35-ee56-4171-ad37-25bd6a0abc49)
![image](https://github.com/user-attachments/assets/eccda6a1-8262-4ec2-83e9-65e109185521)
![image](https://github.com/user-attachments/assets/8bbf4f40-4c35-4a35-afc1-3e9e169c91bf)

Thanks!

**Comment by atc1441** [comment]
Hey, this Manufacturer and type is not supported in this project
