### ISSUE TITLE
Possible problem with "Nightly reboot"

### ISSUE THREAD

**Issue by jurasjo** [OpenEPaperLink/OpenEPaperLink#386]
**Describe the bug**
It is a continuation of this issue: [https://github.com/OpenEPaperLink/Home_Assistant_Integration/issues/188](https://github.com/OpenEPaperLink/Home_Assistant_Integration/issues/188)

I think, because of "Nightly reboot", jobs/automatons might not be properly sent to tags if those are scheduled at this time. 
Now it is clear why I have been observing problems around that particular time.

Looks like this reboot functionality might have something to do with that. Maybe it should be optional or configurable, so it can be set at a time, when there is no planned job.

Full hour might not be the best time for reboot.

**To Reproduce**

Schedule jobs/automations in HA which run around 4:00 and there is a big chance it will not be properly sent to AP/tags, because AP is not available for about 30 sec to 1min at that time.

**Expected behavior**

Reboot of the AP should not interfere with sending data to tags.

**Comment by nlimper** [comment]
I will make it optional, and use 3:56 instead of 4:00

**Comment by jurasjo** [comment]
This sounds great. Thank you.

**Comment by nlimper** [comment]
done, in https://github.com/OpenEPaperLink/OpenEPaperLink/commit/a57c797542536004cba3298d91e1668260b49106

**Comment by jurasjo** [comment]
Thanks for that. So in order to apply this change, the new release must be available?

**Comment by nlimper** [comment]
That's right. There will be a new release shortly.
