### ISSUE TITLE
Update tagtype definitions throws parsing error

### ISSUE THREAD

**Issue by Kristian-R** [OpenEPaperLink/OpenEPaperLink#387]
**Describe the bug**
On a Yellow AP (2.60b) I started the function "update tagtype definitions". After the tagtypes get checked I get the following error message: "Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**To Reproduce**
1. Go to settings page > Manage > Update
2. Click on 'Update tagtype definitions'
3. See error in the console on the right

**Expected behavior**
Error does not appear

**Additional context**
In the tagtypefolder on the ESP there is a Readme.md. After deleting this file the error does not occur again.

**Comment by svenove** [comment]
Fixed five days ago. See #297.
