### ISSUE TITLE
[2.70] Updating Mini AP errors out

### ISSUE THREAD

**Issue by Calimerorulez** [OpenEPaperLink/OpenEPaperLink#390]
Updating a Mini AP to 2.70 errors out on:

```
Updating firmware...
OTA update initiated.
start downloading
http://openepaperlink.eu/getupdate/?url=https%3A%2F%2Fgithub.com%2FOpenEPaperLink%2FOpenEPaperLink%2Freleases%2Fdownload%2F2.70%2FOpenEPaperLink_Mini_AP.bin
Error writing firmware data:
Wrong Magic Byte
```

**Comment by nlimper** [comment]
Keep trying, eventually it will work. 
You can use the 'esp32' button next to the fw version (instead of the big 'update now' button) to skip the filesystem update, which probably already took place.

**Comment by Calimerorulez** [comment]
Thanks Nic, that worked :)
