### ISSUE TITLE
Unable to flash different environment

### ISSUE THREAD

**Issue by Rudios81** [OpenEPaperLink/OpenEPaperLink#392]
It is not possible do flash the ESP32 with a different environment then already flashed via the web gui.

**To Reproduce**
1. Go to the Settings page 
2.Choose update button below.
3. Click the change button next to the repo field
4. Select the desired environment from the list box
5. Click confirm
6. The environment textbox reverts to the current/flashed version of the ESP32 environment

**Expected behavior**
I would expect to be able to select any desired environment, and when selected be able to flash an available binary file onto the ESP32 from the releases list.

**Additional context**
I have created my own pesonal repository, with a custom environment because of custom pinout.
In order to get it running I had to flash my ESP32 from scratch.
If the selection would have worked as intended, I would be able to flash any EPS32 working environment from the original project, even via https://install.openepaperlink.de/ and then afterwards change the repo en environment into my own and flash the ESP32 again. 

I had a short discussion about this issue on a Dutch forum with Nic and there was a thougth it would only be a cosmetic thing, because if the selection of the environment is confirmed with the confirm button, the correct selection is written into the file /current/apconfig.json.
Unfortunately it is not only cosmetic. After selecting any of the available environments for the choosen repo, the release table is filled with available releases for the running environment, not the choosen one. Clicking the ESP32 update button indicates that the current environment binary file is being downloadad and flashed onto the device

**Comment by nlimper** [comment]
Thanks for the detailed description.
Fixed in https://github.com/OpenEPaperLink/OpenEPaperLink/commit/a6772c6fae3a4561c6f350246bf9f52600a52345
It was a frontend problem. To fix, replace `/www/ota.js.gz` with the updated file (and make sure it's refreshed from the cache in your browser).
