### ISSUE TITLE
Feature request: SubGhz support in the default esp32-c6 firmware

### ISSUE THREAD

**Issue by rbtying** [OpenEPaperLink/OpenEPaperLink#393]
**Is your feature request related to a problem? Please describe.**
I installed firmware 2.70 of the openepaperlink firmware on a yellow AP, and I use the subghz support with a cc1110 attached to the esp32-c6. When I updated the esp32-c6 firmware, the AP no longer detected subghz support and my tags no longer updated.

Re-flashing skiphansen's esp32-c6 firmware resolved the problem

**Describe the solution you'd like**
The "update esp32-c6 firmware" should update to a subghz-compatible esp32 firmware

**Describe alternatives you've considered**

**Additional context**

**Comment by nlimper** [comment]
Done, updated the 'download latest' c6 firmware to the SubGHz version (which also works without problem on C6's without SubGHz module).
