### ISSUE TITLE
Feature request: Digi

### ISSUE THREAD

**Issue by chrisdal2000** [OpenEPaperLink/OpenEPaperLink#395]
Can any help me with that?
https://device.report/m/6c35165a563ee24126330f61bff159a5cdf49a7641bd2119886c686324ca0b5f.pdf

Is a https://device.report/digi/ product.
How i can put a new firmare and then can upload a image from a esp32?

thanks

**Comment by jonasniesner** [comment]
Those look nice because they have BWRY. How many of them do you have?

**Comment by chrisdal2000** [comment]
hi, many (20+).
They have a program for sending the logo but not like and i want to make i new if i can,

**Comment by jonasniesner** [comment]
https://github.com/OpenEPaperLink/Tag_FW_EFR32xG22 would be a good starting point. You can also try to ask around on the discord server.

**Comment by chrisdal2000** [comment]
Thanks for your time.

Can you have a link for discord server. I dont use it.

**Comment by jonasniesner** [comment]
https://discord.gg/eRUHt4u5CZ

**Comment by chrisdal2000** [comment]
Do you know where to buy new epaper same that (from ebay, amazon ...) and can put i firmware and can then upload the image with vb.net + esp32 ?
thanks
