### ISSUE TITLE
Error Adding Current Weather to 5.85-inch Tag - "File not found" and HTTP Code -1

### ISSUE THREAD

**Issue by MagnusErler** [OpenEPaperLink/OpenEPaperLink#407]
I encountered an issue while trying to add current weather information to my 5.85-inch tag. The process fails with a "File not found" error and an HTTP code -1. Below are the logs

```18:04:09 File not found. /temp/000005E406B3E3D1.raw
18:04:09 [httpGetJson] http https://api.open-meteo.com/v1/forecast?latitude=55.67594&longitude=12.56553&current_weather=true&windspeed_unit=ms&timezone=Europe/Copenhagen code -1
18:03:55 get weather
18:03:55 Updating 000005E406B3E3D1
18:03:54 Ok, saved
```

![image](https://github.com/user-attachments/assets/19e839c1-989e-47ad-86b8-45e8cd910049)

**Comment by nlimper** [comment]
Probably your AP doesn't have full internet access, or the DNS settings configuration is incorrect. If you use a fixed IP address, check your DNS settings in `/setup`.
