### ISSUE TITLE
Repro-Bug after Update from 7.0 to 7.5?

### ISSUE THREAD

**Issue by gitpower2017** [OpenEPaperLink/OpenEPaperLink#409]
After the update from 7.0 to 7.5 the repositories are wrong?
See the two pictures?
![updat1](https://github.com/user-attachments/assets/2ad6ed38-b879-4ac6-ad19-ba323d1aa8ca)
![updat2](https://github.com/user-attachments/assets/b8f50493-9152-49fb-adbb-38d5227d72e1)

**Comment by atc1441** [comment]
@gitpower2017 to fix it you can click on the change button and reselect the correct enviroment.

Why it happens is also unclear to me, maybe its some difference between updated APs from a specific version in the past vs. newer flashed ones

**Comment by gitpower2017** [comment]
Thanks. I change manual and it is work
