### ISSUE TITLE
Tag dead after update to "universal fw"

### ISSUE THREAD

**Issue by Chellux** [OpenEPaperLink/OpenEPaperLink#412]
hi. i have some "hanshow nebular 3,5" " tags, i tryed update one via the accesspoint, now its dead..

it shows on the AP site, i can change the pictore, but it dont refresh the tag. its frozen :/

and also i cant find the old firmware and the flasher software :/

**Comment by Chellux** [comment]
its shows up at FAFA***** but dont refresh..
![Unbenannt](https://github.com/user-attachments/assets/12b79d9e-c559-4b7f-a594-6f024aa4bda1)


also dont show up as a BT device

**Comment by atc1441** [comment]
Please try to flasher another one of the firmwares then
